name: Build Monochrome APK
on: 
  workflow_dispatch: # This allows you to trigger the build manually

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout Code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: '18'

      - name: Setup Java (Required for Android SDK)
        uses: actions/setup-java@v4
        with:
          distribution: 'zulu'
          java-version: '17'

      - name: Make the build script executable
        run: chmod +x ./build-android.sh

      - name: Run the Build Script
        run: ./build-android.sh

      - name: Upload Finished APK
        uses: actions/upload-artifact@v4
        with:
          name: Monochrome-App
          path: '**/*.apk' 
